### ISSUE TITLE
&nbsp; should not be changed to a space

### ISSUE THREAD

**Issue by tibistibi** [OWASP/java-html-sanitizer#43] opened 2015-09-22 10:35 UTC
test case:

        @Test
        public void testSpace() {
            String text = "L&amp;nbsp;&amp;nbsp;&amp;nbsp;L";
            assertEquals(text, Sanitizers.FORMATTING.sanitize(text));
         }

why:
1)
a &amp;nbsp; is something different than a space. when i get a &amp;nbsp; from my richttext editor i want to preserve it. in the above example when i would add the sanitized text into an html page it would look like L L instead of L&nbsp;&nbsp;&nbsp;L.
2)
i want to know if the user added something wrong and present an error:

		if (!StringUtils.equals(text, clean)) {
			addFieldError("wrong input! please check cleaned text");
		}

i don't want this to happen after a spcae replacement.

todo:
remove the &amp;nbsp; to space part or make it optional.

work around: 
replace the &amp;nbsp; by spaces. do the sanitizing and checking and re add the &amp;nbsp;

**Comment by tibistibi** [comment] 2015-09-22 10:49
in the HtmlSanitizer text gets decoded. this should not be done when sanitizing or be optional:

in the sanitize method:

        case TEXT:
          balancer.text(
              Encoding.decodeHtml(html.substring(token.start, token.end)));

**Comment by mikesamuel** [comment] 2015-10-01 16:38
Duplicate of issue 30.

**Closed by mikesamuel** 2015-10-01 16:38 UTC
Labels: duplicate

**Comment by mikesamuel** [comment] 2015-10-02 18:14
If you're going to do string comparison, instead of doing

```java
String inputString = ...;
String sanitizedString = HTMLSanitizer.sanitize(inputString, myPolicy);
if (inputString.equals(sanitizedString)) {
  // Assume no tags or attributes rejected
} else {
  // Assume some tags or attributes rejected
}
```

why not do

```java
String inputString = ...;
String normalizedString = HTMLSanitizer.sanitize(inputString, policyThatAllowsEverything);
String sanitizedString = HTMLSanitizer.sanitize(inputString, myPolicy);
if (normalizedString.equals(sanitizedString)) {
  // Assume no tags or attributes rejected
} else {
  // Assume some tags or attributes rejected
}
```
?

That should make your equality test independent of any changes in the way text nodes are represented.

**Comment by tibistibi** [comment] 2015-10-02 18:29
thanks that is a smart work around for the problem of giving feedback. the spaces and &nbsp; i could find and replace after the sanitization.
 
i talked to our pen testers and they don't see the need for the text encoding as long as the tags are removed. i also spoke to our db-er and he was very unhappy with the encoding as then he would need to expended  all the fields 5 times to accommodate the longer texts. 
so i think i still will remove the encoding

**Comment by tibistibi** [comment] 2015-10-02 18:34
for others apart from the work around from mikesamuel you can alse use the HtmlChangeListener to track removed tags like this:

        public class MyHtmlChangeListener implements HtmlChangeListener<List<String>> {
	public void discardedTag(List<String> context, String elementName) {
		if (context != null) {
			context.add(elementName);
		}
	}

	public void discardedAttributes(List<String> context, String tagName, String... attributeNames) {
		for (String attributeName : attributeNames) {
			if (context != null) {
				context.add(attributeName);
			}
		}
	}
        }

**Comment by mikesamuel** [comment] 2015-10-02 19:24
> so i think i still will remove the encoding

Fair enough.  When you fork, I'd appreciate if you'd change the package from `org.owasp` to avoid confusion with the OWASP endorsed version.

I also won't be held responsible for informing forks of emerging threats, so you'll have to track those yourself.

**Comment by tibistibi** [comment] 2015-10-02 19:26
yes thanks. i have to check if i'm allowed to add my code into the public domain.

**Comment by mikesamuel** [comment] 2015-10-02 19:31
> yes thanks. i have to check if i'm allowed to add my code into the public domain.

I think "public domain" has a specific legal meaning.  This project is not public domain; it has been released under the [Apache 2](https://github.com/OWASP/java-html-sanitizer/blob/master/COPYING) license and section 4 specifies obligations related to redistribution of modifications.

**Comment by tibistibi** [comment] 2015-10-02 19:33
mmm yes you are right... maybe i'm not allowed to change it than. i will let the project manager think about that :smile:
